default_stages:
    - pre-commit
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.13
      hooks:
          # Run the linter.
          - id: ruff-check
          # Run the formatter.
          - id: ruff-format
    - repo: https://github.com/pre-commit/pre-commit-hooks
      # Pre-commit hooks version.
      rev: v5.0.0
      hooks:
          # Remove trailing whitespaces (spaces at the end of lines).
          - id: trailing-whitespace
          # Makes sure files end in a newline and only a newline.
          - id: end-of-file-fixer
          # Attempts to load all yaml files to verify syntax.
          - id: check-yaml
          # Attempts to load all json files to verify syntax.
          - id: check-json
          # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
          - id: check-case-conflict
          # Checks for a common error of placing code before the docstring.
          - id: check-docstring-first
          # Check for debugger imports and py37+ breakpoint() calls in python source.
          - id: debug-statements
          # Checks for the existence of private keys.
          - id: detect-private-key
